import type { Payment } from "./types";

// 18 synthetic pending payments across 4 fake merchants on a Razorpay-style
// payments platform. Deliberately mixes:
//  - obvious impersonation scams (urgent/verify language, brand-new payee,
//    new device, off-hours)
//  - mule-pattern payments (fast fan-out to unfamiliar payees/devices,
//    no manipulative language)
//  - clearly benign, routine business payments (payroll, rent, vendors)
// so the rules engine has real texture to sort through.

export const SEED_PAYMENTS: Payment[] = [
  {
    id: "PAY-10231",
    merchant: "Chai Point Retail",
    amount: 82_000,
    payeeName: "Suresh Nair",
    payeeAgeDays: 0,
    memo: "URGENT: verify your account immediately or KYC will be suspended",
    channel: "UPI",
    deviceIsNew: true,
    transfersIn24h: 1,
    hourOfDay: 1,
    initiatedBy: "Store Ops Account",
  },
  {
    id: "PAY-10232",
    merchant: "Chai Point Retail",
    amount: 18_500,
    payeeName: "Deepa Traders",
    payeeAgeDays: 412,
    memo: "Monthly tea leaf supply invoice #4471",
    channel: "Bank Transfer",
    deviceIsNew: false,
    transfersIn24h: 1,
    hourOfDay: 11,
    initiatedBy: "Founder's Account",
  },
  {
    id: "PAY-10233",
    merchant: "Chai Point Retail",
    amount: 4_200,
    payeeName: "Amit Sharma",
    payeeAgeDays: 190,
    memo: "Payroll - store staff, October",
    channel: "UPI",
    deviceIsNew: false,
    transfersIn24h: 2,
    hourOfDay: 10,
    initiatedBy: "Store Ops Account",
  },
  {
    id: "PAY-10234",
    merchant: "Chai Point Retail",
    amount: 65_000,
    payeeName: "New Vendor Solutions",
    payeeAgeDays: 1,
    memo: "final notice: confirm your bank details to avoid penalty",
    channel: "Bank Transfer",
    deviceIsNew: true,
    transfersIn24h: 4,
    hourOfDay: 23,
    initiatedBy: "Founder's Account",
  },
  {
    id: "PAY-20101",
    merchant: "Kirana Express",
    amount: 3_000,
    payeeName: "Ramesh Grocers",
    payeeAgeDays: 730,
    memo: "Weekly stock settlement",
    channel: "UPI",
    deviceIsNew: false,
    transfersIn24h: 1,
    hourOfDay: 15,
    initiatedBy: "Shop Owner Account",
  },
  {
    id: "PAY-20102",
    merchant: "Kirana Express",
    amount: 55_000,
    payeeName: "Priya Verma",
    payeeAgeDays: 0,
    memo: "refund pending, please verify OTP to release",
    channel: "UPI",
    deviceIsNew: true,
    transfersIn24h: 3,
    hourOfDay: 2,
    initiatedBy: "Supplier Desk",
  },
  {
    id: "PAY-20103",
    merchant: "Kirana Express",
    amount: 120_000,
    payeeName: "Landlord - Anand Estates",
    payeeAgeDays: 900,
    memo: "Q3 shop rent",
    channel: "Bank Transfer",
    deviceIsNew: false,
    transfersIn24h: 1,
    hourOfDay: 12,
    initiatedBy: "Shop Owner Account",
  },
  {
    id: "PAY-20104",
    merchant: "Kirana Express",
    amount: 9_800,
    payeeName: "Fresh Farms Co-op",
    payeeAgeDays: 60,
    memo: "Produce delivery, September batch",
    channel: "UPI",
    deviceIsNew: false,
    transfersIn24h: 2,
    hourOfDay: 9,
    initiatedBy: "Supplier Desk",
  },
  {
    id: "PAY-20105",
    merchant: "Kirana Express",
    amount: 41_000,
    payeeName: "Rohit Malhotra",
    payeeAgeDays: 2,
    memo: "advance for festival stock",
    channel: "UPI",
    deviceIsNew: true,
    transfersIn24h: 5,
    hourOfDay: 3,
    initiatedBy: "Shop Owner Account",
  },
  {
    id: "PAY-30051",
    merchant: "Bharat EduTech",
    amount: 15_000,
    payeeName: "Sneha Reddy",
    payeeAgeDays: 250,
    memo: "Freelance content review, September",
    channel: "UPI",
    deviceIsNew: false,
    transfersIn24h: 1,
    hourOfDay: 14,
    initiatedBy: "Finance Desk",
  },
  {
    id: "PAY-30052",
    merchant: "Bharat EduTech",
    amount: 98_000,
    payeeName: "Global Cert Partners",
    payeeAgeDays: 0,
    memo: "urgent payment required to reactivate partner account, act now",
    channel: "Bank Transfer",
    deviceIsNew: true,
    transfersIn24h: 1,
    hourOfDay: 0,
    initiatedBy: "Founder's Account",
  },
  {
    id: "PAY-30053",
    merchant: "Bharat EduTech",
    amount: 6_500,
    payeeName: "AWS India",
    payeeAgeDays: 640,
    memo: "Cloud hosting - monthly",
    channel: "Bank Transfer",
    deviceIsNew: false,
    transfersIn24h: 1,
    hourOfDay: 13,
    initiatedBy: "Finance Desk",
  },
  {
    id: "PAY-30054",
    merchant: "Bharat EduTech",
    amount: 28_000,
    payeeName: "Karan Mehta",
    payeeAgeDays: 1,
    memo: "loan disbursal to friend, personal",
    channel: "UPI",
    deviceIsNew: true,
    transfersIn24h: 4,
    hourOfDay: 22,
    initiatedBy: "Founder's Account",
  },
  {
    id: "PAY-30055",
    merchant: "Bharat EduTech",
    amount: 2_100,
    payeeName: "Office Chai Wala",
    payeeAgeDays: 300,
    memo: "Pantry supplies",
    channel: "UPI",
    deviceIsNew: false,
    transfersIn24h: 1,
    hourOfDay: 16,
    initiatedBy: "Finance Desk",
  },
  {
    id: "PAY-40011",
    merchant: "Namma Logistics",
    amount: 71_500,
    payeeName: "Fleet Fuel Partners",
    payeeAgeDays: 45,
    memo: "Diesel bulk purchase, fleet #12",
    channel: "Bank Transfer",
    deviceIsNew: false,
    transfersIn24h: 2,
    hourOfDay: 17,
    initiatedBy: "Fleet Ops Account",
  },
  {
    id: "PAY-40012",
    merchant: "Namma Logistics",
    amount: 33_000,
    payeeName: "Unknown Payee 8827",
    payeeAgeDays: 0,
    memo: "kyc verification refund - confirm your details now",
    channel: "UPI",
    deviceIsNew: true,
    transfersIn24h: 6,
    hourOfDay: 4,
    initiatedBy: "Payroll Desk",
  },
  {
    id: "PAY-40013",
    merchant: "Namma Logistics",
    amount: 12_400,
    payeeName: "Driver Welfare Fund",
    payeeAgeDays: 500,
    memo: "Monthly driver welfare contribution",
    channel: "Bank Transfer",
    deviceIsNew: false,
    transfersIn24h: 1,
    hourOfDay: 10,
    initiatedBy: "Fleet Ops Account",
  },
  {
    id: "PAY-40014",
    merchant: "Namma Logistics",
    amount: 8_900,
    payeeName: "Warehouse Staff - Batch 2",
    payeeAgeDays: 220,
    memo: "Overtime payout, warehouse team",
    channel: "UPI",
    deviceIsNew: false,
    transfersIn24h: 3,
    hourOfDay: 18,
    initiatedBy: "Payroll Desk",
  },
];
